/*
 * Copyright (c) 2017, The Dattack team (http://www.dattack.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dattack.dbping.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;

/**
 * Configuration of a task executed by dbPing. The list of configurable properties are:
 *
 * <ul>
 * <li>command-provider: name of the {@link com.dattack.dbping.engine.SqlCommandProvider} class to be used by this
 * task to order the execution of queries. Currently the possible values are:
 * <ul>
 * <li>{@link com.dattack.dbping.engine.SqlCommandRandomProvider}</li>
 * <li>{@link com.dattack.dbping.engine.SqlCommandRoundRobinProvider}</li>
 * <li>{@link com.dattack.dbping.engine.SqlCommandWeightedRandomProvider}</li>
 * </ul>
 * This parameter is optional (default: com.dattack.dbping.engine.SqlCommandRoundRobinProvider)
 * </li>
 * <li>context: list of {@link ContextBean} used by this task. This list is optional.</li>
 * <li>datasource: name of the JNDI resource of type DataSource used by this task. This parameter is mandatory.</li>
 * <li>executions: number of iterations of the task. This parameter is optional (default: -1, endless loop)</li>
 * <li>log-file: path to the output file containing the data generated by this task. This parameter is mandatory.</li>
 * <li>name: the name of the task. This parameter is mandatory.</li>
 * <li>query or script: list of queries and SQL scripts to be executed by this task. This parameter is mandatory.</li>
 * <li>threads: number of threads used by the task. This parameter is optional (default: 1)</li>
 * <li>timeBetweenExecutions: number of milliseconds the task will wait before starting a new execution. This
 * parameter is optional (default: 0)</li>
 * </ul>
 *
 * <p>Example:</p>
 * <pre>{@code
 *     <task name="..." datasource="jndi/..." executions="-1" threads="1" timeBetweenExecutions="0">
 *         <command-provider>...</command-provider>
 *         <context>...</context>
 *         <context>...</context>
 *         <log-file>...</log-file>
 *         <query>...</query>
 *         <query>...</query>
 *         <script>...</script>
 *         <query>...</query>
 *         <script>...</script>
 *     </task>
 * }</pre>
 *
 * @author cvarela
 * @since 0.1
 */
@SuppressWarnings("PMD.DataClass")
public class PingTaskBean implements Serializable {

    private static final long serialVersionUID = 3640559668991529501L;

    private String commandProvider;
    private List<ContextBean> contextBeanList;
    private String datasource;
    private int executions;
    private String logFile;
    private String name;
    private List<SqlCommandBean> sqlStatementList;
    private int threads;
    private int timeBetweenExecutions;

    public PingTaskBean() {
        this.contextBeanList = new ArrayList<>();
        this.executions = -1;
        this.sqlStatementList = new ArrayList<>();
        this.threads = 1;
        this.timeBetweenExecutions = 0;
    }

    /**
     * Returns the command provider.
     *
     * @return the commandProvider
     */
    public String getCommandProvider() {
        return commandProvider;
    }

    @XmlAttribute(name = "strategy")
    public void setCommandProvider(final String commandProvider) {
        BeanHelper.checkDeprecatedVariables(commandProvider, "strategy");
        this.commandProvider = BeanHelper.normalizeToEmpty(commandProvider);
    }

    public List<ContextBean> getContextBeanList() {
        return contextBeanList;
    }

    @XmlElement(name = "context")
    public void setContextBeanList(final List<ContextBean> contextBeanList) {
        this.contextBeanList = contextBeanList;
    }

    /**
     * Returns the datasource.
     *
     * @return the datasource
     */
    public String getDatasource() {
        return datasource;
    }

    @XmlAttribute(required = true)
    public void setDatasource(final String datasource) {
        BeanHelper.checkDeprecatedVariables(datasource, "datasource");
        this.datasource = BeanHelper.normalizeToEmpty(datasource);
    }

    /**
     * Returns the number of executions.
     *
     * @return the number of executions
     */
    public int getExecutions() {
        return executions;
    }

    @XmlAttribute
    public void setExecutions(final int executions) {
        this.executions = executions;
    }

    /**
     * Returns the log file to use.
     *
     * @return the log file to use
     */
    public String getLogFile() {
        return logFile;
    }

    @XmlAttribute(name = "log", required = true)
    public void setLogFile(final String logFile) {
        BeanHelper.checkDeprecatedVariables(logFile, "log");
        this.logFile = BeanHelper.normalizeToEmpty(logFile);
    }

    /**
     * Returns the task name.
     *
     * @return the task name
     */
    public String getName() {
        return name;
    }

    @XmlAttribute(required = true)
    public void setName(final String name) {
        BeanHelper.checkDeprecatedVariables(name, "name");
        this.name = BeanHelper.normalizeToEmpty(name);
    }

    /**
     * Returns the list of sentences to be executed.
     *
     * @return the list of sentences to be executed
     */
    public List<SqlCommandBean> getSqlStatementList() {
        return sqlStatementList;
    }

    @XmlElements({ //
        @XmlElement(name = "query", type = SqlStatementBean.class), //
        @XmlElement(name = "script", type = SqlScriptBean.class) //
    })
    public void setSqlStatementList(final List<SqlCommandBean> sqlStatementList) {
        this.sqlStatementList = sqlStatementList;
    }

    /**
     * The number of threads to be executed concurrently.
     *
     * @return the number of threads to be executed concurrently.
     */
    public int getThreads() {
        return threads;
    }

    @XmlAttribute
    public void setThreads(final int threads) {
        this.threads = Math.max(threads, 1);
    }

    /**
     * Returns the waiting time between two consecutive iterations.
     *
     * @return the waiting time between two consecutive iterations
     */
    public int getTimeBetweenExecutions() {
        return timeBetweenExecutions;
    }

    @XmlAttribute
    public void setTimeBetweenExecutions(final int timeBetweenExecutions) {
        this.timeBetweenExecutions = Math.max(timeBetweenExecutions, 0);
    }
}
